GestionQuejasSP/GestionQuejasSP/urls.py
from django.contrib import admin
from django.urls import path, include
from Usuario import urls
from django.conf import settings
from django.conf.urls.static import static
from . import consumers

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include('Autenticacion.url')),
    path('dash/', include('GestionQuejasAPP.url')),
    path('usuario/', include(urls)),
    path('quejasU/', include('QuejasUsuarios.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

websocket_urlpatterns = [
    path('ws/notificaciones/', consumers.NotificacionesConsumer.as_asgi()),
]

GestionQuejasSP/Usuario/urls.py
from django.urls import path
from .views import user_list, create_user, edit_user, group_create, group_edit, group_list, \
    password_change_done, ClasificacionListView, ClasificacionDeleteView, ClasificacionUpdateView, \
    ClasificacionCreateView, \
    conclusion_new, conclusion_delete, conclusion_edit, enti_new, enti_delete, enti_edit, satis_delete, satis_edit, \
    satis_new, caso_delete, caso_edit, caso_new, moda_new, moda_delete, moda_edit, via_new, via_edit, via_delete, \
    procedencia_edit, procedencia_delete, procedencia_new, confirmiar_eliminacion, confirmiar_eliminacion_group, \
    crear_usuario

from django.contrib.auth.views import PasswordChangeView
from .views import MyPasswordChangeView

urlpatterns = [

    # User Crud
    path('', user_list, name='user_list'),
    path('create/', create_user, name='user_create'),
    path('registro_user/', crear_usuario, name='registro_user'),
    path('update/<int:pk>/', edit_user, name='user_update'),
    path('confirmiar_eliminacion/<int:pk>/', confirmiar_eliminacion, name='confirmiar_eliminacion'),

    # Grupo crud
    path('grupoE/<int:pk>/', group_edit, name='grupoE'),
    path('confirmiar_eliminacion_grupo/<int:pk>/', confirmiar_eliminacion_group, name='confirmiar_eliminacion_grupo'),
    path('grupoC/', group_create, name='grupoC'),
    path('grupoL/', group_list, name='grupoL'),


    # Cambiar Contraseña
    path('cambiar-contrasena/', MyPasswordChangeView.as_view(),
         name='change_password'),
    path('pasword_change/', password_change_done, name='password_change_done'),


    # Clasificacion crud
    path('delete_clas/<int:pk>/', ClasificacionDeleteView.as_view(), name='delete'),
    path('edit/<int:pk>/', ClasificacionUpdateView.as_view(), name='edit'),
    path('clasificacion/', ClasificacionCreateView.as_view(), name='clasificacion'),
    path('listas/',  ClasificacionListView.as_view(), name='list_desp'),

    # Conclusion crud
    path('conclusion_new/', conclusion_new, name='conclusion_new'),
    path('conclusion_delete/<int:pk>/', conclusion_delete, name='conclusion_delete'),
    path('conclusion_edit/<int:pk>/', conclusion_edit, name='conclusion_edit'),

    # Entidad crud
    path('create_enti/', enti_new, name='create_enti'),
    path('enti_delete/<int:pk>/', enti_delete, name='enti_delete'),
    path('enti_edit/<int:pk>/', enti_edit, name='enti_edit'),

    # satisfaccion crud
    path('create_satis/', satis_new, name='create_satis'),
    path('satis_delete/<int:pk>/', satis_delete, name='satis_delete'),
    path('satis_edit/<int:pk>/', satis_edit, name='satis_edit'),

    # CasoscPrensas crud
    path('create_caso/', caso_new, name='create_caso'),
    path('caso_delete/<int:pk>/', caso_delete, name='caso_delete'),
    path('caso_edit/<int:pk>/', caso_edit, name='caso_edit'),

    # moda crud
    path('create_moda/', moda_new, name='create_moda'),
    path('moda_delete/<int:pk>/', moda_delete, name='moda_delete'),
    path('moda_edit/<int:pk>/', moda_edit, name='moda_edit'),

# via crud
    path('create_via/', via_new, name='create_via'),
    path('via_delete/<int:pk>/', via_delete, name='via_delete'),
    path('via_edit/<int:pk>/', via_edit, name='via_edit'),

# procedencia crud
    path('create_procedencia/', procedencia_new, name='create_procedencia'),
    path('procedencia_delete/<int:pk>/', procedencia_delete, name='procedencia_delete'),
    path('procedencia_edit/<int:pk>/', procedencia_edit, name='procedencia_edit'),





]

GestionQuejasSP/Usuario/forms.py
from django import forms
from django.contrib.auth.models import User,Group,Permission
from django.contrib.auth.forms import UserCreationForm,UserChangeForm
from django.contrib.auth import get_user_model
from django.http import HttpResponseForbidden
from django.views.generic.edit import UpdateView
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy


class UserForm(forms.ModelForm):
    group = forms.ModelChoiceField(queryset=Group.objects.all())

    class Meta:
        model = User
        fields = ['username', 'email', 'password', 'first_name', 'last_name', 'is_active', 'is_staff']
        widgets = {
            'password': forms.PasswordInput(),
        }

    def clean_email(self):
        email = self.cleaned_data['email']
        if not email:
            raise forms.ValidationError('Email is required.')
        return email

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
        return user

    def save(self, commit=True):
        user = super(UserForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
            user.groups.add(self.cleaned_data['group'])
        return user


class CustomUserCreationForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=True)
    last_name = forms.CharField(max_length=30, required=True)
    email = forms.EmailField(max_length=254, required=True)
    groups = forms.ModelMultipleChoiceField(
        queryset=Group.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )
    is_active = forms.BooleanField(required=False, initial=True, widget=forms.CheckboxInput)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'groups', 'is_active', 'password1', 'password2')





class GroupForm(forms.ModelForm):
    name = forms.CharField(max_length=15)
    permissions = forms.ModelMultipleChoiceField(
        queryset=Permission.objects.all(),
        widget=forms.CheckboxSelectMultiple(),
        required=False
    )

    class Meta:
        model = Group
        fields = ['name', 'permissions']


class UserEditForm(UserChangeForm):
    groups = forms.ModelMultipleChoiceField(
        queryset=Group.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )
    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name', 'is_active', 'groups']







from GestionQuejasAPP.models import Clasificacion,EntidadAfectada,Modalidad,Via,Procedencia,CasoPrensa,Satisfaccion,Conclusion

class ClasificacionForm(forms.ModelForm):

    class Meta:
        model = Clasificacion
        fields = ('nombre',)


class EntidadAfectadaForm(forms.ModelForm):
    class Meta:
        model = EntidadAfectada
        fields = ('nombre',)

class ModalidadForm(forms.ModelForm):
    class Meta:
        model = Modalidad
        fields = ('nombre',)

class ViaForm(forms.ModelForm):
    class Meta:
        model = Via
        fields = ('nombre',)

class ProcedenciaForm(forms.ModelForm):
    class Meta:
        model = Procedencia
        fields = ('nombre',)

class CasoPrensaForm(forms.ModelForm):
    class Meta:
        model = CasoPrensa
        fields = ('nombre',)

class SatisfaccionForm(forms.ModelForm):
    class Meta:
        model = Satisfaccion
        fields = ('nombre',)

class ConclusionForm(forms.ModelForm):
    class Meta:
        model = Conclusion
        fields = ('nombre',)




class CrearUsuarioFormulario(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'password1', 'password2', 'email')

GestionQuejasSP/templates/Gestionar Usuario/change_password.html
{% extends 'base.html' %}

{% block content %}

{#  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">#}
{#  <link rel="stylesheet" href="styles.css">#}

  <style>
    form#changePasswordForm {
      margin-top: 100px;
      display: flex;
      flex-direction: column;
      align-items: center;
    }

    .form-group {
      margin-bottom: 30px;
      width: 80%; /* Cambia el ancho para adaptarse a la vista móvil */
      max-width: 400px; /* Establece un ancho máximo para el formulario */
      color: #1e1f22;
    }

    /* Media query para estilos específicos en la vista móvil */
    @media (max-width: 768px) {
      form#changePasswordForm {
        margin-top: 50px;
      }

      .form-group {
        width: 100%; /* Ocupa el ancho completo en la vista móvil */
        max-width: none; /* Elimina el ancho máximo en la vista móvil */
      }
    }

    label {
      font-weight: bold;
      color: #1e1f22;
      font-family: Arial;
    }

    input[type="password"] {
      width: 100%;
      padding: 10px;
      border: none;
      border-bottom: 2px solid #1e1f22;
      background-color: rgb(255, 255, 255);
      transition: border-color 0.3s ease;
      color: #1e1f22; /* Cambia el color del texto a blanco */
    }

    input[type="password"]:focus {
      background: linear-gradient(to right, rgb(83, 159, 39), rgb(73, 143, 32), rgb(62, 121, 27), rgb(51, 98, 24));
      -webkit-background-clip: text;
      -webkit-text-fill-color: transparent;
      outline: none;
      border-image: linear-gradient(to right, rgb(83, 159, 39), rgb(73, 143, 32), rgb(62, 121, 27), rgb(51, 98, 24)) 2 stretch;
    }

    button[type="submit"] {
      padding: 10px 20px;
      border: none;
      border-radius: 5px;
      color: white;
      font-weight: bold;
      cursor: pointer;
    }

    button[type="submit"]:hover {
      opacity: 0.8;
    }
  </style>


  <form id="changePasswordForm" method="post" style="margin-top: 50px;margin-left:20px;margin-right: 20px;">
    {% csrf_token %}
    <div class="form-group" >
      <label for="{{ form.old_password.id_for_label }}">Contraseña Actual</label>
      {{ form.old_password }}
    </div>
    <div class="form-group">
      <label for="{{ form.new_password1.id_for_label }}">Nueva Contraseña</label>
      {{ form.new_password1 }}
    </div>
    <div class="form-group">
      <label for="{{ form.new_password2.id_for_label }}">Confirmar Nueva Contraseña</label>
      {{ form.new_password2 }}
    </div>
    <div>
      <button type="submit" class="btn btn-primary" style="background-color: #529e26;border-color: #529d27;border-radius: 0;width: 200px;float:left;margin-right:10px;font-size: 15px; font-family: Arial; font-weight: bold; margin-bottom: 10px;">Cambiar Contraseña</button>
      <button type="button" onclick="window.location.href='{% url 'dash' %}'" class="btn btn-secondary mr-2 text-center" style="background-color: #444444;border-color:#444444 ;border-radius: 0;width: 200px;float:left; height: 44px;font-size: 15px;font-family: Arial; font-weight:bold;">
        Volver
      </button>
    </div>
  </form>

{#  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>#}
{#  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>#}
{#  <script src="script.js"></script>#}

<!-- Coloca este código en la sección <head> del HTML para cargar jQuery -->
{#<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>#}






{% endblock %}

GestionQuejasSP/templates/Gestionar Usuario/confirmar_eliminacion_de_grupo.html
  <p style="font-size: 20px; color: black">¿Estás seguro que deseas eliminar el grupo "{{ group.name }}"?</p>
  <form method="post" action="{{ request.path }}" >
    {% csrf_token %}
        <div style="float: right;">
    <input type="submit"  class="btn btn-danger" value="Eliminar" style="background-color: #008bff;border-color: #008bff;border-radius: 0;">
   <button id="cancelarBtn" type="button" class="btn btn-secondary" style="background-color: #444444;border-color:#444444 ;border-radius: 0;">Cancelar</button>
        </div>
  </form>


<script>
  // Obtén una referencia al botón de cancelar
  var cancelarBtn = document.getElementById("cancelarBtn");

  // Agrega un evento de clic al botón
  cancelarBtn.addEventListener("click", function() {
    // Cierra la ventana modal
    var modal = document.getElementById("exampleModal");
    var bootstrapModal = bootstrap.Modal.getInstance(modal);
    bootstrapModal.hide();
  });
</script>

GestionQuejasSP/templates/Gestionar Usuario/confirmar_eliminacion_de_usuario.html
  <p style="font-size: 20px; color: black">¿Estás seguro que deseas eliminar el usuario "{{ user.username }}"?</p>
  <form method="post" action="{{ request.path }}" >
    {% csrf_token %}
      <div style="float: right;">
    <input type="submit" class="btn btn-danger" value="Eliminar" style="background-color: #008bff;border-color: #008bff;border-radius: 0;">
          <button id="cancelarBtn" type="button" class="btn btn-secondary"  style="background-color: #444444;border-color:#444444 ;border-radius: 0;">Cancelar </button>
     </div>
  </form>


<script>
  // Obtén una referencia al botón de cancelar
  var cancelarBtn = document.getElementById("cancelarBtn");

  // Agrega un evento de clic al botón
  cancelarBtn.addEventListener("click", function() {
    // Cierra la ventana modal
    var modal = document.getElementById("exampleModal");
    var bootstrapModal = bootstrap.Modal.getInstance(modal);
    bootstrapModal.hide();
  });
</script>

GestionQuejasSP/templates/Gestionar Usuario/crearGrupo.html
{% extends "base.html" %}

{% load static %}

{% block content %}




<link href="{% static  'css/insertar.css' %}" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        width: 100%;
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }


      .bd-mode-toggle {
        z-index: 1500;
      }
    </style>


    <!-- Custom styles for this template -->
    <link href="checkout.css" rel="stylesheet">




    <meta charset="UTF-8">

<div class="container">
  <div class="py-5 text-center">
    <img class="d-block mx-auto mb-4" src="{% static 'Autenticacion/login/img/S.png' %}" alt="" width="200" height="150">
    <h2 style="color: #1e1f22">Crear Grupo</h2>
  </div>
  <form method="post">
    {% csrf_token %}
    <div class="row">
      <div class="col-md-6">
        <div class="form-group" style="margin-left: 30px">
          <label for="{{ form.name.id_for_label }}" style="font-size: 17px;color: #1e1f22">Nombre del Grupo:</label>
           <input type="text" class="form-control" name="name" maxlength="15" required="" id="id_name" style="background-color: transparent;width: 300px;
border: 1px solid #1e1f22 ; color: #1e1f22">
          <button type="submit" class="btn btn-primary" style="background-color: #529e26;border-color: #529d26;border-radius: 0;margin-top: 20px" >Guardar</button>
        </div>
      </div>
      <div class="col-md-6" style="color: #1e1f22;background-color: white;box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);margin-left: 550px;margin-top: -150px">
        <div class="row">
          <div class="col-md-6">
            <div class="form-group" style="color: #1e1f22">
              <label style="font-size: 17px; font-weight: bold;color: #1e1f22" >Permisos:</label>
              {% for permission in form.permissions %}
              {% if forloop.counter|divisibleby:2 %}
            </div>
          </div>
          <div class="col-md-6">
            <div class="form-group">
              {% endif %}
              <div class="form-check form-check-inline">
                {{ permission }}
              </div>
              {% endfor %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </form>
</div>
 {% endblock %}
{#<script>#}
{#$(document).ready(function() {#}
{#    $('.permission-select').on('dblclick', function() {#}
{#        $(this).appendTo('.selected-permissions');#}
{#    });#}
{##}
{#    $('.selected-permissions').on('dblclick', '.permission-select', function() {#}
{#        $(this).appendTo('.permission-container');#}
{#    });#}
{##}
{#    $('#form').on('submit', function() {#}
{#        $('.permission-select').prop('selected', true);#}
{#    });#}
{#});#}
{#</script#}

GestionQuejasSP/templates/Gestionar Usuario/editarGrupo.html
{% extends "base.html" %}

{% load static %}

{% block content %}




<link href="{% static  'css/insertar.css' %}" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        width: 100%;
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }

      .bd-mode-toggle {
        z-index: 1500;
      }
    </style>





    <meta charset="UTF-8">

<div class="container">
  <div class="py-5 text-center" >
      <img class="d-block mx-auto mb-4"  src="{% static 'Autenticacion/login/img/S.png' %}" alt="" width="200" height="150" >
      <h2 style="color: #1e1f22">Editar Grupo</h2>
    </div>

<form method="post" class="form-horizontal">
  {% csrf_token %}
  <div class="form-group" style="margin-left: 30px">
   <label  style="font-size: 17px;color: #1e1f22">Nombre del Grupo:</label>

      <input type="text"  class="form-control" name="name" value="{{ group.name }}" maxlength="15" required="" id="id_name" style="background-color: transparent;width: 300px;
border: 1px solid #1e1f22 ; color: #1e1f22">
      <div class="form-group" style="margin-top: 20px">
    <button type="submit" class="btn btn-primary" style="background-color: #529e26;border-color: #529d26">Guardar</button>
    <a href="{% url 'grupoL' %}" class="btn btn-secondary">Cancelar</a>
  </div>
  </div>


   <div class="col-md-6" style="color: #1e1f22;margin-left: 550px;margin-top: -160px;box-shadow: 0 0 10px rgba(0, 0, 0, 0.1)">
        <div class="row">
          <div class="col-md-6">
            <div class="form-group" style="color: #1e1f22">
              <label style="font-size: 17px; font-weight: bold;color: #1e1f22" >Permisos:</label>
              {% for permission in form.permissions %}
              {% if forloop.counter|divisibleby:2 %}
            </div>
          </div>
          <div class="col-md-6">
            <div class="form-group">
              {% endif %}
              <div class="form-check form-check-inline">
                {{ permission }}
              </div>
              {% endfor %}
            </div>
          </div>
        </div>
      </div>



</form>
</div>


     {% endblock %}

GestionQuejasSP/templates/Gestionar Usuario/password_change_done.html
{% extends 'base.html' %}

{% block content %}
  <h1>Contraseña cambiada </h1>

{% endblock %}

GestionQuejasSP/templates/Gestionar Usuario/user_form2.html
{% extends "base.html" %}

{% load static %}

{% block content %}

     <style>

input[type="checkbox"]:checked {
  background-color: green !important;
  border-color: green !important;
  color: white !important;
}


    </style>



    <div class="container py-5 text-center">
        <img class="d-block mx-auto mb-4" src="{% static 'Autenticacion/login/img/S.png' %}" alt="" width="200" height="150">
        <h2 style="color: #1e1f22">Editar Usuario</h2>
    </div>

    {% if error_message %}
        <div class="alert alert-danger" role="alert">
            {{ error_message|safe }}
        </div>
    {% endif %}

    <form id="editUserForm" method="POST" action="{{ request.path }}">
        {% csrf_token %}
       <div class="col-md-10 col-lg-8" style="position: absolute; left: 50%; transform: translateX(-50%); color: #1e1f22">
    <div class="row">
   <div class="col-sm-6 mb-3">
            <label for="username" style="color:#1e1f22">Nombre de usuario:</label>
            <input type="text" class="form-control" name="username"  maxlength="150" required="" id="username" value="{{ user.username }}" style="background-color: #ffffff;color: #1e1f22;border-radius: 0">
        </div>
         <div class="col-sm-6 mb-3">
            <label for="email">Correo:</label>
            <input type="email" class="form-control" name="email" maxlength="254" id="id_email" value="{{ user.email }}" style="background-color: #ffffff;color: #1e1f22;border-radius: 0">
        </div>
        <div class="col-sm-6 mb-3">
            <label for="fullName">Nombre:</label>
            <input type="text " class="form-control" name="first_name" maxlength="150" id="id_first_name"  value="{{  user.first_name }}" style="background-color: #ffffff;color: #1e1f22;border-radius: 0">
        </div>
      <div class="col-sm-6 mb-3">
            <label for="fullName">Apellidos:</label>
            <input type="text" class="form-control" name="last_name" maxlength="150" id="id_last_name" value="{{  user.last_name }}" style="background-color: #ffffff;color: #1e1f22;border-radius: 0">
        </div>
         <div class="col-12 col-lg-6 mb-3">
            Activo
            <input type="checkbox" name="is_active" id="id_is_active" value="{{ user.is_active }}" checked="">
        </div>





<style>
    .btn-group-toggle .btn {
        background-color: white;
        color: #529d26;
    }

    .btn-group-toggle .btn.active {
        background-color: #529d26;
        color: white;
    }
</style>

<div class="col-12 col-lg-6 mb-3">
    <label for="groups">Grupo:</label>
    <div class="btn-group-toggle" data-toggle="buttons">
        {% for group in form.groups %}
            <label class="btn btn-secondary">
                {{ group }}
            </label>
        {% endfor %}
    </div>
</div>




        <div style="display: flex; flex-direction: column; justify-content: center; align-items: center; height: 10vh;">
            <div style="position: absolute; left: 50%; transform: translateX(-50%);">
                <button class="btn btn-primary btn-lg" type="submit" style="background-color: #529e26;border-color: #529d26;border-radius: 0;width: 200px;float:left; height: 48px;font-size: 15px;font-family: Arial; font-weight:bold;margin-right: 10px ">
                    Actualizar
                </button>
                <a href="{% url 'dash' %}" class="btn btn-secondary mr-2" style="background-color: #444444;border-color:#444444 ;border-radius: 0;width: 200px;float:left; height: 48px;font-size: 1.25rem;margin-right: 20px">
    Volver
  </a>

            </div>
        </div>
    </div>
       </div>
    </form>


                    <div style="height: 20px;">
      <span style="display: inline-block; width: 20px; height: 20px; background-color: transparent;"></span>
  </div>
{% endblock %}

GestionQuejasSP/templates/Gestionar Usuario/user_prueba_create.html
{% extends "base.html" %}

{% load static %}

{% block content %}

{# <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">#}

    <div class="container py-5 text-center">
        <img class="d-block mx-auto mb-4" src="{% static 'Autenticacion/login/img/S.png' %}" alt="" width="200" height="150">
        <h2 style="color: #1e1f22">Agregar Usuario</h2>
    </div>



{% if error_message %}
    <div class="alert alert-danger" role="alert">
        {{ error_message|safe }}
    </div>
{% endif %}
<form id="insertUserForm" method="POST" action="{{ request.path }}" >
  {% csrf_token %}
 <div class="col-md-10 col-lg-8" style="position: absolute; left: 50%; transform: translateX(-50%); color: #1e1f22">
    <div class="row">
    <div class="col-sm-6 mb-3">
        <label for="username">Nombre de usuario:</label>
        <input type="text" class="form-control" maxlength="30" autofocus="" name="username" required="" id="username" data-listener-added_8192cc54="true" style="background-color: #ffffff;color: #1e1f22;border-radius: 0">
    </div>
    <div class="col-sm-6 mb-3">
        <label for="email">Correo:</label>
        <input type="email" class="form-control" name="email" maxlength="254" required="" id="id_email" style="background-color: #ffffff;color: #1e1f22;border-radius: 0">
    </div>
    <div class="col-sm-6 mb-3">
        <label for="fullName">Nombre:</label>
        <input type="text" class="form-control" name="first_name" maxlength="30" required="" id="id_first_name" style="background-color: #ffffff;color: #1e1f22;border-radius: 0">
    </div>
    <div class="col-sm-6 mb-3">
        <label for="fullName">Apellidos:</label>
        <input type="text" class="form-control" name="last_name" maxlength="30" required="" id="id_last_name" style="background-color: #ffffff;color: #1e1f22;border-radius: 0">
    </div>
    <div class="col-12 col-lg-6 mb-3">
        <label for="password">Contraseña:</label>
        <input type="password" class="form-control" name="password1" autocomplete="new-password" required="" id="id_password1" style="background-color: #ffffff;color: #1e1f22;border-radius: 0">
    </div>
    <div class="col-12 col-lg-6 mb-3">
        <label for="confirmPassword">Confirmar Contraseña:</label>
        <input type="password" class="form-control" name="password2" autocomplete="new-password" required="" id="id_password2" style="background-color: #ffffff;color: #1e1f22;border-radius: 0">
    </div>
    <div class="col-12 col-lg-6 mb-3">
        <label for="isActive">Activo:</label>
        <input type="checkbox" name="is_active" id="id_is_active" checked="" style="background-color: #ffffff;color: #1e1f22;border-radius: 0">
    </div>
</div>




<style>
    .btn-group-toggle .btn {
        background-color: white;
        color: #529d26;
    }

    .btn-group-toggle .btn.active {
        background-color: #529d26;
        color: white;
    }
</style>

<div class="col-12 col-lg-6 mb-3">
    <label for="groups">Grupo:</label>
    <div class="btn-group-toggle" data-toggle="buttons">
        {% for group in form.groups %}
            <label class="btn btn-secondary">
                {{ group }}
            </label>
        {% endfor %}
    </div>
</div>




     <div style="margin-bottom: 20px; justify-items: center">
<button class="btn btn-primary btn-lg" type="submit" style="background-color: #529e26;border-color: #529d26; border-radius: 0; width: 150px;height: 45px ">
    Insertar
</button>
<a href="{% url 'dash' %}" class="btn btn-secondary mr-2" style="background-color: #444444;border-color:#444444 ;border-radius: 0;width: 150px;float:left; height: 45px;font-size: 1.25rem;margin-right: 20px">
    Volver
  </a>
</div>
</div>


                    <div style="height: 80px;">
      <span style="display: inline-block; width: 20px; height: 20px; background-color: transparent;"></span>
  </div>


     </div>
 </div>
      </form>
  {% endblock %}